insert into texte (idTexte,codeTexte,codeLangue,texte) Values ("1","accueil","FR","Accueil");
insert into texte (idTexte,codeTexte,codeLangue,texte) Values ("2","accueil","EN","Home");
insert into texte (idTexte,codeTexte,codeLangue,texte) Values ("3","administrateur","FR","Administrateur");
insert into texte (idTexte,codeTexte,codeLangue,texte) Values ("4","administrateur","EN","Administrator");
insert into texte (idTexte,codeTexte,codeLangue,texte) Values ("5","adressemail","FR","Adresse Email");
insert into texte (idTexte,codeTexte,codeLangue,texte) Values ("6","adressemail","EN","Email Adress");
insert into texte (idTexte,codeTexte,codeLangue,texte) Values ("7","ajouter","FR","Ajouter");
insert into texte (idTexte,codeTexte,codeLangue,texte) Values ("8","ajouter","EN ","Add");
insert into texte (idTexte,codeTexte,codeLangue,texte) Values ("9","confirmationMdp","FR","Confirmation du mot de passe");
insert into texte (idTexte,codeTexte,codeLangue,texte) Values ("10","confirmationMdp","EN","Pasword Confirmation");
insert into texte (idTexte,codeTexte,codeLangue,texte) Values ("11","connexion","FR","Connexion");
insert into texte (idTexte,codeTexte,codeLangue,texte) Values ("12","connexion","EN","Connection");
insert into texte (idTexte,codeTexte,codeLangue,texte) Values ("13","consulter","FR","Consulter");
insert into texte (idTexte,codeTexte,codeLangue,texte) Values ("14","consulter","EN","View");
insert into texte (idTexte,codeTexte,codeLangue,texte) Values ("15","creer","FR","Créer le compte");
insert into texte (idTexte,codeTexte,codeLangue,texte) Values ("16","creer","EN","Create account");
insert into texte (idTexte,codeTexte,codeLangue,texte) Values ("17","creerCompte","FR","Création du compte");
insert into texte (idTexte,codeTexte,codeLangue,texte) Values ("18","creerCompte","EN","Account creation");
insert into texte (idTexte,codeTexte,codeLangue,texte) Values ("19","deconnexion","FR","deconnexion");
insert into texte (idTexte,codeTexte,codeLangue,texte) Values ("20","deconnexion","EN","disconnection");
insert into texte (idTexte,codeTexte,codeLangue,texte) Values ("21","droitsUtilisateur","FR","Droits Utilisateurs");
insert into texte (idTexte,codeTexte,codeLangue,texte) Values ("22","droitsUtilisateur","EN","User rights");
insert into texte (idTexte,codeTexte,codeLangue,texte) Values ("23","inscription","FR","Inscription");
insert into texte (idTexte,codeTexte,codeLangue,texte) Values ("24","inscription","EN","Registration");
insert into texte (idTexte,codeTexte,codeLangue,texte) Values ("25","listeUtilisateurs","FR","Liste des Utilisateurs");
insert into texte (idTexte,codeTexte,codeLangue,texte) Values ("26","listeUtilisateurs","EN","Users List");
insert into texte (idTexte,codeTexte,codeLangue,texte) Values ("27","modifier","FR","Modifier");
insert into texte (idTexte,codeTexte,codeLangue,texte) Values ("28","modifier","EN","Modify");
insert into texte (idTexte,codeTexte,codeLangue,texte) Values ("29","motDePasse","FR","Mot de passe");
insert into texte (idTexte,codeTexte,codeLangue,texte) Values ("30","motDePasse","EN","Password");
insert into texte (idTexte,codeTexte,codeLangue,texte) Values ("31","nom","FR","Nom");
insert into texte (idTexte,codeTexte,codeLangue,texte) Values ("32","nom","EN","Last Name");
insert into texte (idTexte,codeTexte,codeLangue,texte) Values ("33","pageConnexion","FR","Page de Connexion");
insert into texte (idTexte,codeTexte,codeLangue,texte) Values ("34","pageConnexion","EN","Login Page");
insert into texte (idTexte,codeTexte,codeLangue,texte) Values ("35","phraseBienvenue","FR","Bienvenue sur le site");
insert into texte (idTexte,codeTexte,codeLangue,texte) Values ("36","phraseBienvenue","EN","Welcome");
insert into texte (idTexte,codeTexte,codeLangue,texte) Values ("37","prenom","FR","Prénom");
insert into texte (idTexte,codeTexte,codeLangue,texte) Values ("38","prenom","EN ","Last Name");
insert into texte (idTexte,codeTexte,codeLangue,texte) Values ("39","rechercher","FR","Rechercher");
insert into texte (idTexte,codeTexte,codeLangue,texte) Values ("40","rechercher","EN","Search");
insert into texte (idTexte,codeTexte,codeLangue,texte) Values ("41","retour","FR","Retour");
insert into texte (idTexte,codeTexte,codeLangue,texte) Values ("42","retour","EN","return");
insert into texte (idTexte,codeTexte,codeLangue,texte) Values ("43","sauvegarder","FR","Sauvegarder");
insert into texte (idTexte,codeTexte,codeLangue,texte) Values ("44","sauvegarder","EN","Save Changes");
insert into texte (idTexte,codeTexte,codeLangue,texte) Values ("45","supprimer","FR","Supprimer");
insert into texte (idTexte,codeTexte,codeLangue,texte) Values ("46","supprimer","EN","Delete");
insert into texte (idTexte,codeTexte,codeLangue,texte) Values ("47","telephone","FR","Téléphone");
insert into texte (idTexte,codeTexte,codeLangue,texte) Values ("48","telephone","EN ","Phone ");
insert into texte (idTexte,codeTexte,codeLangue,texte) Values ("49","utilisateur","FR","Utilisateur");
insert into texte (idTexte,codeTexte,codeLangue,texte) Values ("50","utilisateur","EN","User");
